export const mockExercises = [
  {
    name: "Supino Reto",
    category: "Peito",
    sets: "4",
    reps: "10-12",
    weight: "60",
  },
  {
    name: "Agachamento",
    category: "Pernas",
    sets: "4",
    reps: "8-10",
    weight: "80",
  },
  {
    name: "Remada Curvada",
    category: "Costas",
    sets: "3",
    reps: "10-12",
    weight: "50",
  },
  {
    name: "Desenvolvimento de Ombros",
    category: "Ombros",
    sets: "3",
    reps: "10-12",
    weight: "30",
  },
  {
    name: "Rosca Direta",
    category: "Bíceps",
    sets: "3",
    reps: "12-15",
    weight: "20",
  },
  {
    name: "Tríceps Corda",
    category: "Tríceps",
    sets: "3",
    reps: "12-15",
    weight: "25",
  },
  {
    name: "Elevação Lateral",
    category: "Ombros",
    sets: "3",
    reps: "12-15",
    weight: "10",
  },
  {
    name: "Leg Press",
    category: "Pernas",
    sets: "4",
    reps: "10-12",
    weight: "150",
  },
  {
    name: "Puxada na Frente",
    category: "Costas",
    sets: "3",
    reps: "10-12",
    weight: "60",
  },
  {
    name: "Flexão Plantar",
    category: "Panturrilhas",
    sets: "4",
    reps: "15-20",
    weight: "100",
  },
]

